name: MUZAFFAR GLOBAL TRADE UZ - Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Android APK yaratish
    runs-on: ubuntu-latest

    steps:
      - name: GitHub kodini yuklash
        uses: actions/checkout@v4

      - name: Java 17 ni o‘rnatish
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle o‘rnatish
        uses: gradle/actions/setup-gradle@v4

      - name: Android APK yaratish
        run: gradle assembleDebug --no-daemon

      - name: APK faylini saqlash
        uses: actions/upload-artifact@v4
        with:
          name: MUZAFFAR-GLOBAL-TRADE-UZ-APK
          path: app/build/outputs/apk/debug/app-debug.apk
